name: PR Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: windows-latest

    env:
      SOLUTION: 'DemoSolution.sln'
      BUILD_CONFIGURATION: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION }} --no-build --verbosity normal
